/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package groupassignment;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

import static org.junit.jupiter.api.Assertions.*;
//tests
@SpringBootTest
class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    //Smoke test
    @Test void contextLoads(){
    }


}
