/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package groupassignment;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;
@Tag("SmokeTest")
public class SmokeTests {


    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }



    //Smoke test
    @Test void contextLoads() {
    }


}
